### ISSUE TITLE
fppdWatcher.sh not compatible with FPPv8.x

### ISSUE THREAD

**Issue by compufritz** [FalconChristmas/fpp-scripts#13]
The fppdWatcher.sh script and by extension the fppdWatcherStart.sh scripts aren't compatible with FPPv8.x and will cause fppd to crash every 30 seconds or so.

fppdWatcher.sh runs a curl statement against fppjson.php to determine the status of fppd (running, stopped, etc). The statement in question is this one:
`curl -m 2 http://localhost/fppjson.php?command=getFPPstatus 2> /dev/null | grep '"running"' > /dev/null`

fppjson.php doesn't exist in FPPv8.x so the script doesn't see fppd running and stops it and then restarts it and will continue to loop like that until the watcher script process is killed.

I believe changing that line of code in the script to this `curl -m 2 http://localhost/api/fppd/status 2> /dev/null | grep '"running"' > /dev/null` will fix the issue, but I haven't tested as of yet. Also, not 100% sure if the script is needed anymore either or if there is another method to monitor fppd status and restart it if needed.

PR will be submitted upon testing of the suggested changes.

**Comment by darylc** [comment]
In general these scripts are old and unloved and there are better ways to achieve the same things these days.  Based on your feedback, I've marked this script as incompatible with fpp v8.x+  I don't believe it is required anymore, certainly if I kill fppd it automatically restarts without this script being involved.

**Comment by compufritz** [comment]
Thanks @darylc.
