### ISSUE TITLE
syntax error in PlayEffectWhenNotPlayingFSEQ

### ISSUE THREAD

**Issue by johna777** [FalconChristmas/fpp-scripts#7]
/home/fpp/media/scripts/PlayEffectWhenNotPlayingFSEQ.sh: line 33: syntax error near unexpected token `else'
 /home/fpp/media/scripts/PlayEffectWhenNotPlayingFSEQ.sh: line 33: `            else'

FPP 6.3, Raspberry Pi, Bullseye Raspberry OS

**Comment by darylc** [comment]
These days you fpp will automatically play background.eseq if nothing is running
